[project]
name = "pregnancy-hypothyroidism"
version = "2.1.0"
description = "Deep learning applied to pregnancy complications"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "dragon-ml-toolbox[ml]==20.7.1",
]

[dependency-groups]
dev = [
    "nbstripout>=0.8.2",
]
